<head>
	<meta charset="utf-8">
	<!-- Make every page mobile friendly -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Alternative Music</title>
	<!-- Add bootstrap -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Add jQuery and fail safe in case CDN doesn't load -->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="js/jquery-1.12.4.min.js"><\/script>')</script>
</head>