<nav class="navbar navbar-default">
	<div class="container-fluid">
		<ul class="nav navbar-nav">
			<li <?php if ($thisPage == "Index") echo "class=\"active\"" ?>><a href="index.php">HOME</a></li>
			<li <?php if ($thisPage == "NMH") echo "class=\"active\"" ?>><a href="NMH.php">NEUTRAL MILK HOTEL</a></li>
			<li <?php if ($thisPage == "LH") echo "class=\"active\"" ?>><a href="lordHuron.php">LORD HURON</a></li>
			<li <?php if ($thisPage == "FW") echo "class=\"active\"" ?>><a href="freelanceWhales.php">FREELANCE WHALES</a></li>
		</ul>
	</div>
</nav>
<br>