
	<nav>
		<ul>
			<li <?php if ($thisPage == "Index") echo "class=\"active\"" ?>><a href="index.php">Home</a></li>
			<li <?php if ($thisPage == "NMH") echo "class=\"active\"" ?>><a href="NMH.php">Neutral Milk Hotel</a></li>
			<li <?php if ($thisPage == "LH") echo "class=\"active\"" ?>><a href="lordHuron.php">Lord Huron</a></li>
			<li <?php if ($thisPage == "FW") echo "class=\"active\"" ?>><a href="freelanceWhales.php">Freelance Whales</a></li>
		</ul>
	</nav>
	<br>